# Generated by Django 3.1.1 on 2020-09-29 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomClient', models.CharField(max_length=250)),
                ('PostNomCli', models.CharField(max_length=250)),
                ('PreNomCli', models.CharField(max_length=250)),
                ('AddressCli', models.CharField(max_length=250)),
                ('NumTelCli', models.CharField(max_length=250)),
                ('mailCli', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Addmail', models.EmailField(max_length=254)),
                ('Client', models.CharField(max_length=250)),
                ('sujet', models.CharField(max_length=250)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeFourni', models.CharField(max_length=250)),
                ('NomFourni', models.CharField(max_length=250)),
                ('PostNomFourni', models.CharField(max_length=250)),
                ('PreNomFourni', models.CharField(max_length=250)),
                ('AddressFourni', models.CharField(max_length=250)),
                ('NumTelFourni', models.CharField(max_length=250)),
                ('mailFourni', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Magasinier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeMag', models.CharField(max_length=250)),
                ('NomMag', models.CharField(max_length=250)),
                ('NumTelMaga', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Marchandise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageMarch', models.FileField(upload_to='marchandise')),
                ('CodeMarch', models.CharField(max_length=250)),
                ('NomMarch', models.CharField(max_length=250)),
                ('Designation', models.TextField()),
                ('Quantity', models.CharField(max_length=250)),
                ('PrixUnitaire', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marchimg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiadvert.marchandise')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered')], max_length=200, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiadvert.client')),
                ('marchandise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiadvert.marchandise')),
            ],
        ),
    ]
