# Generated by Django 3.1.1 on 2020-09-29 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiadvert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marchandise',
            name='Magasinier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiadvert.magasinier'),
        ),
        migrations.AddField(
            model_name='marchandise',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='digiadvert.fournisseur'),
        ),
    ]
