# Generated by Django 3.1.1 on 2020-10-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiadvert', '0003_auto_20201016_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='AddressCli',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='AddressFourni',
        ),
    ]
